"use strict";

try{
    x = 10;
    //miFuncion();
} catch(error){
    console.log(error);
}finally{ //* Siempre se va a ejecutar
    console.log("Termina la revisi√≥n de errores");
}
